add_newline = false
command_timeout = 200
format = """
$hostname\
$sudo\
$username\
[$directory$git_branch$git_status]($style)\
$character"""
right_format = """
$python\
$dart\
$bun\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$rust\
$shell\
"""

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = "\\$ "
staged     = "+ "
renamed    = ""
deleted    = "✘ "

[python]
format = '\[[py ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[bun]
format = '\[[bun ($version)]($style)\]'

[dart]
format = '\[[dart ($version)]($style)\]'

[golang]
format = '\[[go ($version)]($style)\]'

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '

[java]
format = '\[[java ($version)]($style)\]'

[kotlin]
format = '\[[kts ($version)]($style)\]'

[lua]
format = '\[[lua ($version)]($style)\]'

[nodejs]
format = '\[[node ($version)]($style)\]'

[rust]
format = '\[[rs ($version)]($style)\]'

[shell]
format = '\[[sh $indicator]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[username]
format = '\[[$user]($style)\]'

